// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cache) DeepCopyInto(out *Cache) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cache.
func (in *Cache) DeepCopy() *Cache {
	if in == nil {
		return nil
	}
	out := new(Cache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mba) DeepCopyInto(out *Mba) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mba.
func (in *Mba) DeepCopy() *Mba {
	if in == nil {
		return nil
	}
	out := new(Mba)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Plugins) DeepCopyInto(out *Plugins) {
	*out = *in
	out.Pstate = in.Pstate
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Plugins.
func (in *Plugins) DeepCopy() *Plugins {
	if in == nil {
		return nil
	}
	out := new(Plugins)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pstate) DeepCopyInto(out *Pstate) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pstate.
func (in *Pstate) DeepCopy() *Pstate {
	if in == nil {
		return nil
	}
	out := new(Pstate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rdt) DeepCopyInto(out *Rdt) {
	*out = *in
	out.Cache = in.Cache
	out.Mba = in.Mba
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rdt.
func (in *Rdt) DeepCopy() *Rdt {
	if in == nil {
		return nil
	}
	out := new(Rdt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RmdConfig) DeepCopyInto(out *RmdConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RmdConfig.
func (in *RmdConfig) DeepCopy() *RmdConfig {
	if in == nil {
		return nil
	}
	out := new(RmdConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RmdConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RmdConfigList) DeepCopyInto(out *RmdConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RmdConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RmdConfigList.
func (in *RmdConfigList) DeepCopy() *RmdConfigList {
	if in == nil {
		return nil
	}
	out := new(RmdConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RmdConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RmdConfigSpec) DeepCopyInto(out *RmdConfigSpec) {
	*out = *in
	if in.RmdNodeSelector != nil {
		in, out := &in.RmdNodeSelector, &out.RmdNodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RmdConfigSpec.
func (in *RmdConfigSpec) DeepCopy() *RmdConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RmdConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RmdConfigStatus) DeepCopyInto(out *RmdConfigStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RmdConfigStatus.
func (in *RmdConfigStatus) DeepCopy() *RmdConfigStatus {
	if in == nil {
		return nil
	}
	out := new(RmdConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RmdNodeState) DeepCopyInto(out *RmdNodeState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RmdNodeState.
func (in *RmdNodeState) DeepCopy() *RmdNodeState {
	if in == nil {
		return nil
	}
	out := new(RmdNodeState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RmdNodeState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RmdNodeStateList) DeepCopyInto(out *RmdNodeStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RmdNodeState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RmdNodeStateList.
func (in *RmdNodeStateList) DeepCopy() *RmdNodeStateList {
	if in == nil {
		return nil
	}
	out := new(RmdNodeStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RmdNodeStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RmdNodeStateSpec) DeepCopyInto(out *RmdNodeStateSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RmdNodeStateSpec.
func (in *RmdNodeStateSpec) DeepCopy() *RmdNodeStateSpec {
	if in == nil {
		return nil
	}
	out := new(RmdNodeStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RmdNodeStateStatus) DeepCopyInto(out *RmdNodeStateStatus) {
	*out = *in
	if in.Workloads != nil {
		in, out := &in.Workloads, &out.Workloads
		*out = make(map[string]WorkloadMap, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(WorkloadMap, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RmdNodeStateStatus.
func (in *RmdNodeStateStatus) DeepCopy() *RmdNodeStateStatus {
	if in == nil {
		return nil
	}
	out := new(RmdNodeStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RmdWorkload) DeepCopyInto(out *RmdWorkload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RmdWorkload.
func (in *RmdWorkload) DeepCopy() *RmdWorkload {
	if in == nil {
		return nil
	}
	out := new(RmdWorkload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RmdWorkload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RmdWorkloadList) DeepCopyInto(out *RmdWorkloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RmdWorkload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RmdWorkloadList.
func (in *RmdWorkloadList) DeepCopy() *RmdWorkloadList {
	if in == nil {
		return nil
	}
	out := new(RmdWorkloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RmdWorkloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RmdWorkloadSpec) DeepCopyInto(out *RmdWorkloadSpec) {
	*out = *in
	if in.CoreIds != nil {
		in, out := &in.CoreIds, &out.CoreIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ReservedCoreIds != nil {
		in, out := &in.ReservedCoreIds, &out.ReservedCoreIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Rdt = in.Rdt
	out.Plugins = in.Plugins
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RmdWorkloadSpec.
func (in *RmdWorkloadSpec) DeepCopy() *RmdWorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(RmdWorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RmdWorkloadStatus) DeepCopyInto(out *RmdWorkloadStatus) {
	*out = *in
	if in.WorkloadStates != nil {
		in, out := &in.WorkloadStates, &out.WorkloadStates
		*out = make(map[string]WorkloadState, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RmdWorkloadStatus.
func (in *RmdWorkloadStatus) DeepCopy() *RmdWorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(RmdWorkloadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in WorkloadMap) DeepCopyInto(out *WorkloadMap) {
	{
		in := &in
		*out = make(WorkloadMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadMap.
func (in WorkloadMap) DeepCopy() WorkloadMap {
	if in == nil {
		return nil
	}
	out := new(WorkloadMap)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadState) DeepCopyInto(out *WorkloadState) {
	*out = *in
	if in.CoreIds != nil {
		in, out := &in.CoreIds, &out.CoreIds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Rdt = in.Rdt
	out.Plugins = in.Plugins
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadState.
func (in *WorkloadState) DeepCopy() *WorkloadState {
	if in == nil {
		return nil
	}
	out := new(WorkloadState)
	in.DeepCopyInto(out)
	return out
}
