apiVersion: v1
kind: ServiceAccount
metadata:
  name: intel-rmd-operator

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: intel-rmd-node-agent

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: intel-rmd-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - intel-rmd-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - intel.com
  resources:
  - '*'
  - rmdnodestates
  - rmdworkloads
  - rmdconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: intel-rmd-node-agent
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intel.com
  resources:
  - '*'
  - rmdnodestates
  - rmdworkloads
  - rmdconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

---    
    
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: intel-rmd-operator
subjects:
- kind: ServiceAccount
  name: intel-rmd-operator
roleRef:
  kind: Role
  name: intel-rmd-operator
  apiGroup: rbac.authorization.k8s.io

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: intel-rmd-node-agent
subjects:
- kind: ServiceAccount
  name: intel-rmd-node-agent
roleRef:
  kind: Role
  name: intel-rmd-node-agent
  apiGroup: rbac.authorization.k8s.io

---  

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: intel-rmd-operator
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: [""]
  resources: ["nodes/status"] 
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "patch", "create", "update"]
- apiGroups: ["intel.com"]
  resources: ["rmdworkloads", "rmdnodestates", "rmdconfigs"] 
  verbs: ["get", "list", "watch", "patch", "create", "update"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch", "patch", "create", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: intel-rmd-node-agent
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "patch", "create", "update"]
- apiGroups: ["intel.com"]
  resources: ["rmdworkloads"]
  verbs: ["get", "list", "watch", "patch", "create", "update"]

---  
  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: intel-rmd-operator
roleRef:
  kind: ClusterRole
  name: intel-rmd-operator 
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: default 
  name: intel-rmd-operator

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: intel-rmd-node-agent
roleRef:
  kind: ClusterRole
  name: intel-rmd-node-agent 
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: default 
  name: intel-rmd-node-agent
