apiVersion: v1
kind: Pod
metadata:
  generateName: guaranteed-cache-pod-
  annotations:
    container1_cache_min: "2"
    container2_cache_min: "2"    
    container2_mba_percentage: "50"
spec:
  containers:
  - name: container1
    image: ubuntu
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    resources:
      requests:
        memory: "64Mi"
        cpu: 2 
        intel.com/l3_cache_ways: 2
      limits:
        memory: "64Mi"
        cpu: 2
        intel.com/l3_cache_ways: 2
  - name: container2
    image: ubuntu 
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    resources:
      requests:
        memory: "64Mi"
        cpu: 2 
        intel.com/l3_cache_ways: 2
      limits:
        memory: "64Mi"
        cpu: 2
        intel.com/l3_cache_ways: 2
