apiVersion: v1
kind: Pod
metadata:
  generateName: pod-guaranteed-cache-mba-
  labels:
    name: nginx
  annotations:
    nginx1_cache_min: "2"
    nginx1_mba_percentage: "50"
spec:
  containers:
  - name: nginx1
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: 3 
        intel.com/l3_cache_ways: 2
      limits:
        memory: "64Mi"
        cpu: 3
        intel.com/l3_cache_ways: 2
