apiVersion: v1
kind: Pod
metadata:
  generateName: pod-guaranteed-cache-mba-
  annotations:
    container1_cache_min: "2"
    container1_mba_percentage: "50"
spec:
  containers:
  - name: container1 
    image: clearlinux/os-core:latest
    # keep container alive with sleep infinity
    command: [ "sleep" ]
    args: [ "infinity" ]
    resources:
      requests:
        memory: "64Mi"
        cpu: 3 
        intel.com/l3_cache_ways: 2
      limits:
        memory: "64Mi"
        cpu: 3
        intel.com/l3_cache_ways: 2
