apiVersion: intel.com/v1alpha1
kind: RmdWorkload
metadata:
  name: rmdworkload-guaranteed-cache-mba
spec:
  # Add fields here
  coreIds: ["0-3"]
  rdt:
    cache:
      max: 2
      min: 2
    mba:
      percentage: 50      
  nodes: ["worker-node-1","worker-node-2"] 
