apiVersion: intel.com/v1alpha1
kind: RmdWorkload
metadata:
  name: rmdworkload-guaranteed
spec:
  # Add fields here
  allCores: true
  rdt:
    cache:
      max: 2
      min: 2
  nodeSelector:
    feature.node.kubernetes.io/cpu-rdt.RDTL3CA: "true"
