apiVersion: intel.com/v1alpha1
kind: RmdWorkload
metadata:
  name: rmdworkload-guaranteed
spec:
  # Add fields here
  coreIds: ["0-95"]
  rdt:
    cache:
      max: 6 
      min: 6 
  nodes: ["silpixa00400471"] 
