apiVersion: intel.com/v1alpha1
kind: RmdWorkload
metadata:
  name: rmdworkload-guaranteed-cache-mba
spec:
  # Add fields here
  coreIds: ["4", "9"]
  rdt:
    cache:
      max: 2
      min: 2
    mba:
      percentage: 50      
  nodes: ["silpixa00400471"] 
